/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-04-27 05:33:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class recommend_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<!--\r\n");
      out.write("	Editorial by HTML5 UP\r\n");
      out.write("	html5up.net | @ajlkn\r\n");
      out.write("	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)\r\n");
      out.write("-->\r\n");
      out.write("<html>\r\n");
      out.write("	<head>\r\n");
      out.write("		<title>Editorial by HTML5 UP</title>\r\n");
      out.write("		<meta charset=\"utf-8\" />\r\n");
      out.write("		<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("		<!--[if lte IE 8]><script src=\"/common/js/ie/html5shiv.js\"></script><![endif]-->\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"/tourapp/common/css/main.css\" />\r\n");
      out.write("		<!--[if lte IE 9]><link rel=\"stylesheet\" href=\"/common/css/ie9.css\" /><![endif]-->\r\n");
      out.write("		<!--[if lte IE 8]><link rel=\"stylesheet\" href=\"/common/css/ie8.css\" /><![endif]-->\r\n");
      out.write("		\r\n");
      out.write("		<!--추천 여행지 이미지-->\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\">\r\n");
      out.write("		<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.6.4/dist/jquery.slim.min.js\"></script>\r\n");
      out.write("		<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("		<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("		<!--추천-->\r\n");
      out.write("		<link rel=\"icon\" href=\"/tourapp/images/favicon.png\">\r\n");
      out.write("		<!-- Bootstrap CSS -->\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"/tourapp/common/css/bootstrap.min.css\">\r\n");
      out.write("		<!-- animate CSS -->\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"/tourapp/common/css/animate.css\">\r\n");
      out.write("		<!-- owl carousel CSS -->\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"/tourapp/common/css/owl.carousel.min.css\">\r\n");
      out.write("		<!-- themify CSS -->\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"/tourapp/common/css/themify-icons.css\">\r\n");
      out.write("		<!-- flaticon CSS -->\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"/tourapp/common/css/flaticon.css\">\r\n");
      out.write("		<!-- fontawesome CSS -->\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"/tourapp/common/fontawesome/css/all.min.css\">\r\n");
      out.write("		<!-- magnific CSS -->\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"/tourapp/common/css/magnific-popup.css\">\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"/tourapp/common/css/gijgo.min.css\">\r\n");
      out.write("		<!-- niceselect CSS -->\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"/tourapp/common/css/nice-select.css\">\r\n");
      out.write("		<!-- slick CSS -->\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"/tourapp/common/css/slick.css\">\r\n");
      out.write("		<!-- style CSS -->\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"/tourapp/common/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("		<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js\"></script>\r\n");
      out.write("		<script type=\"text/javascript\">\r\n");
      out.write("			$(document).ready(function(){\r\n");
      out.write("				let today = new Date();\r\n");
      out.write("				let month = today.getMonth()+1;\r\n");
      out.write("				if(month>=3 && month<=5){\r\n");
      out.write("					$(\"#season\").css({\"background-image\":\"url(/tourapp/images/spring.jpg)\"});\r\n");
      out.write("				}else if(month>=6 && month<=8){\r\n");
      out.write("					$(\"#season\").css({\"background-image\":\"url(/tourapp/images/summer.jpg)\"});\r\n");
      out.write("				}else if(month>=9 && month<=11){\r\n");
      out.write("					$(\"#season\").css({\"background-image\":\"url(/tourapp/images/autumn.jpg)\"});\r\n");
      out.write("				}else{\r\n");
      out.write("					$(\"#season\").css({\"background-image\":\"url(/tourapp/images/winter.jpg)\"});\r\n");
      out.write("				}\r\n");
      out.write("\r\n");
      out.write("				$(\"#pick\").on(\"click\", function(){\r\n");
      out.write("					var offset = $(\"#view_image\").offset();\r\n");
      out.write("					$('html').animate({scrollTop : offset.top}, 400);\r\n");
      out.write("				});\r\n");
      out.write("				\r\n");
      out.write("			});\r\n");
      out.write("		</script>\r\n");
      out.write("	</head>\r\n");
      out.write("	<body>\r\n");
      out.write("\r\n");
      out.write("		<!-- Wrapper -->\r\n");
      out.write("			<div id=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("				<!-- Main -->\r\n");
      out.write("					<div id=\"main\">\r\n");
      out.write("						<div class=\"inner\">\r\n");
      out.write("\r\n");
      out.write("							<!-- Header -->\r\n");
      out.write("								<header id=\"header\">\r\n");
      out.write("									<a href=\"index.html\" class=\"logo\"><strong>Editorial</strong> by HTML5 UP</a>\r\n");
      out.write("									<ul class=\"icons\">\r\n");
      out.write("										<li><a href=\"#\" class=\"icon fa-twitter\"><span class=\"label\">Twitter</span></a></li>\r\n");
      out.write("										<li><a href=\"#\" class=\"icon fa-facebook\"><span class=\"label\">Facebook</span></a></li>\r\n");
      out.write("										<li><a href=\"#\" class=\"icon fa-snapchat-ghost\"><span class=\"label\">Snapchat</span></a></li>\r\n");
      out.write("										<li><a href=\"#\" class=\"icon fa-instagram\"><span class=\"label\">Instagram</span></a></li>\r\n");
      out.write("										<li><a href=\"#\" class=\"icon fa-medium\"><span class=\"label\">Medium</span></a></li>\r\n");
      out.write("									</ul>\r\n");
      out.write("								</header>\r\n");
      out.write("\r\n");
      out.write("							<!-- banner part start-->\r\n");
      out.write("								<section class=\"banner_part\" id=\"season\">\r\n");
      out.write("									<div class=\"container\">\r\n");
      out.write("										<div class=\"row align-items-center justify-content-center\">\r\n");
      out.write("											<div class=\"col-lg-10\">\r\n");
      out.write("												<div class=\"banner_text text-center\">\r\n");
      out.write("													<div class=\"banner_text_iner\">\r\n");
      out.write("														<p style=\"color:#fff; font-size:3.5em; font-weight: 900;\"> our T our</p>\r\n");
      out.write("														<br/>\r\n");
      out.write("														<p>Let’s start your journey with us, your dream will come true</p>\r\n");
      out.write("														<a href=\"#\" class=\"btn_1\" id=\"pick\">Today's pick</a>\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</section>\r\n");
      out.write("							<!-- banner part start-->\r\n");
      out.write("						\r\n");
      out.write("							<!-- booking part start-->\r\n");
      out.write("								<section class=\"booking_part\" style=\"border: none;\">\r\n");
      out.write("									<div class=\"container\">\r\n");
      out.write("										<div class=\"row\">\r\n");
      out.write("											<div class=\"col-lg-12\">\r\n");
      out.write("												<div class=\"booking_content\">\r\n");
      out.write("													<div class=\"tab-content\" id=\"myTabContent\">\r\n");
      out.write("														<div class=\"tab-pane fade show active\" id=\"hotel\" role=\"tabpanel\" aria-labelledby=\"hotel-tab\">\r\n");
      out.write("															<div class=\"booking_form\">\r\n");
      out.write("																<form action=\"#\">\r\n");
      out.write("																	<div class=\"form-row\">\r\n");
      out.write("																		<div class=\"form_colum\">\r\n");
      out.write("																			<select class=\"nc_select\">\r\n");
      out.write("																				<option selected>Choose place </option>\r\n");
      out.write("																				<option value=\"1\">서울</option>\r\n");
      out.write("																				<option value=\"2\">인천</option>\r\n");
      out.write("																				<option value=\"3\">대전</option>\r\n");
      out.write("																				<option value=\"3\">대구</option>\r\n");
      out.write("																				<option value=\"3\">울산</option>\r\n");
      out.write("																				<option value=\"3\">부산</option>\r\n");
      out.write("																				<option value=\"3\">광주</option>\r\n");
      out.write("																				<option value=\"3\">세종</option>\r\n");
      out.write("																				<option value=\"3\">경기</option>\r\n");
      out.write("																				<option value=\"3\">강원</option>\r\n");
      out.write("																				<option value=\"3\">충청북도</option>\r\n");
      out.write("																				<option value=\"3\">충청남도</option>\r\n");
      out.write("																				<option value=\"3\">전라북도</option>\r\n");
      out.write("																				<option value=\"3\">전라남도</option>\r\n");
      out.write("																				<option value=\"3\">경상북도</option>\r\n");
      out.write("																				<option value=\"3\">경상남도</option>\r\n");
      out.write("																				\r\n");
      out.write("																			</select>\r\n");
      out.write("																		</div>\r\n");
      out.write("																		<div class=\"form_colum\" style=\"width:65%\">\r\n");
      out.write("																			<input id=\"keyword\" placeholder=\"   Search the keywords\" style=\"width:630px; height:50px\">\r\n");
      out.write("																		</div>\r\n");
      out.write("																		<div class=\"form_btn\">\r\n");
      out.write("																			<a href=\"#\" class=\"btn_1\">search</a>\r\n");
      out.write("																		</div>\r\n");
      out.write("																	</div>\r\n");
      out.write("																</form>\r\n");
      out.write("															</div>\r\n");
      out.write("														</div>\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</section>\r\n");
      out.write("							<!-- Header part end-->\r\n");
      out.write("						\r\n");
      out.write("							<!--top place start-->\r\n");
      out.write("								<section class=\"top_place section_padding\" id=\"view_image\">\r\n");
      out.write("									<div class=\"container\">\r\n");
      out.write("										<!-- <div class=\"row justify-content-center\">\r\n");
      out.write("											<div class=\"col-xl-6\">\r\n");
      out.write("												<div class=\"section_tittle text-center\">\r\n");
      out.write("													 <h2>Top Places to visit</h2>\r\n");
      out.write("													<p>Waters make fish every without firmament saw had. Morning air subdue. Our. Air very one. Whales grass is fish whales winged.</p>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div> -->\r\n");
      out.write("\r\n");
      out.write("										<style type=\"text/css\">\r\n");
      out.write("											.travel_image{\r\n");
      out.write("												height:300px;\r\n");
      out.write("												width :510px\r\n");
      out.write("											}\r\n");
      out.write("										</style>\r\n");
      out.write("										<div class=\"row\">\r\n");
      out.write("											<div class=\"col-lg-4 col-md-4\">\r\n");
      out.write("												<div class=\"single_place\">\r\n");
      out.write("													<div class=\"card\" style=\"width:325px\">\r\n");
      out.write("														<img class=\"card-img-top\" src=\"/tourapp/images/single_place_1.png\" alt=\"Card image\" style=\"width:100%\">\r\n");
      out.write("														<div class=\"card-body\">\r\n");
      out.write("														  <h4 class=\"card-title\">Saintmartine Iceland</h4>\r\n");
      out.write("														  <p class=\"card-text\">멋진 해변가. 멋진 비행기</p>\r\n");
      out.write("														  <!-- <a href=\"#\" class=\"btn btn-primary\">view more</a> -->\r\n");
      out.write("														</div>\r\n");
      out.write("													  </div>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("											<div class=\"col-lg-4 col-md-4\">\r\n");
      out.write("												<div class=\"single_place\">\r\n");
      out.write("													<div class=\"card\" style=\"width:325px\">\r\n");
      out.write("														<img class=\"card-img-top\" src=\"/tourapp/images/single_place_2.png\" alt=\"Card image\" style=\"width:100%\">\r\n");
      out.write("														<div class=\"card-body\">\r\n");
      out.write("														  <h4 class=\"card-title\">Saintmartine Iceland</h4>\r\n");
      out.write("														  <p class=\"card-text\">멋진 해변가. 멋진 비행기</p>\r\n");
      out.write("														  <!-- <a href=\"#\" class=\"btn btn-primary\">view more</a> -->\r\n");
      out.write("														</div>\r\n");
      out.write("													  </div>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("											<div class=\"col-lg-4 col-md-4\">\r\n");
      out.write("												<div class=\"single_place\">\r\n");
      out.write("													<div class=\"card\" style=\"width:325px\">\r\n");
      out.write("														<img class=\"card-img-top\" src=\"/tourapp/images/single_place_3.png\" alt=\"Card image\" style=\"width:100%\">\r\n");
      out.write("														<div class=\"card-body\">\r\n");
      out.write("														  <h4 class=\"card-title\">Saintmartine Iceland</h4>\r\n");
      out.write("														  <p class=\"card-text\">멋진 해변가. 멋진 비행기</p>\r\n");
      out.write("														  <!-- <a href=\"#\" class=\"btn btn-primary\">view more</a> -->\r\n");
      out.write("														</div>\r\n");
      out.write("													  </div>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("											<div class=\"col-lg-4 col-md-4\">\r\n");
      out.write("												<div class=\"single_place\">\r\n");
      out.write("													<div class=\"card\" style=\"width:325px\">\r\n");
      out.write("														<img class=\"card-img-top\" src=\"/tourapp/images/single_place_4.png\" alt=\"Card image\" style=\"width:100%\">\r\n");
      out.write("														<div class=\"card-body\">\r\n");
      out.write("														  <h4 class=\"card-title\">Saintmartine Iceland</h4>\r\n");
      out.write("														  <p class=\"card-text\">멋진 해변가. 멋진 비행기</p>\r\n");
      out.write("														  <!-- <a href=\"#\" class=\"btn btn-primary\">view more</a> -->\r\n");
      out.write("														</div>\r\n");
      out.write("													  </div>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("											<div class=\"col-lg-4 col-md-4\">\r\n");
      out.write("												<div class=\"single_place\">\r\n");
      out.write("													<div class=\"card\" style=\"width:325px\">\r\n");
      out.write("														<img class=\"card-img-top\" src=\"/tourapp/images/single_place_4.png\" alt=\"Card image\" style=\"width:100%\">\r\n");
      out.write("														<div class=\"card-body\">\r\n");
      out.write("														  <h4 class=\"card-title\">Saintmartine Iceland</h4>\r\n");
      out.write("														  <p class=\"card-text\">멋진 해변가. 멋진 비행기</p>\r\n");
      out.write("														  <!-- <a href=\"#\" class=\"btn btn-primary\">view more</a> -->\r\n");
      out.write("														</div>\r\n");
      out.write("													  </div>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("			\r\n");
      out.write("										</div>\r\n");
      out.write("										<div style=\"text-align : center;\">\r\n");
      out.write("											<a href=\"#\" class=\"btn_1 text-cnter\">Discover more</a>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</section>\r\n");
      out.write("							<!--top place end-->\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				\r\n");
      out.write("			\r\n");
      out.write("\r\n");
      out.write("				<!-- Sidebar -->\r\n");
      out.write("					<div id=\"sidebar\">\r\n");
      out.write("						<div class=\"inner\">\r\n");
      out.write("\r\n");
      out.write("							<!-- Search -->\r\n");
      out.write("								<section id=\"search\" class=\"alt\">\r\n");
      out.write("									<form method=\"post\" action=\"#\">\r\n");
      out.write("										<input type=\"text\" name=\"query\" id=\"query\" placeholder=\"Search\" />\r\n");
      out.write("									</form>\r\n");
      out.write("								</section>\r\n");
      out.write("\r\n");
      out.write("							<!-- Menu -->\r\n");
      out.write("								<nav id=\"menu\">\r\n");
      out.write("									<header class=\"major\">\r\n");
      out.write("										<h2>Menu</h2>\r\n");
      out.write("									</header>\r\n");
      out.write("									<ul>\r\n");
      out.write("										<li><a href=\"index.html\">Homepage</a></li>\r\n");
      out.write("										<li><a href=\"generic.html\">Generic</a></li>\r\n");
      out.write("										<li><a href=\"elements.html\">Elements</a></li>\r\n");
      out.write("										<li>\r\n");
      out.write("											<span class=\"opener\">Submenu</span>\r\n");
      out.write("											<ul>\r\n");
      out.write("												<li><a href=\"#\">Lorem Dolor</a></li>\r\n");
      out.write("												<li><a href=\"#\">Ipsum Adipiscing</a></li>\r\n");
      out.write("												<li><a href=\"#\">Tempus Magna</a></li>\r\n");
      out.write("												<li><a href=\"#\">Feugiat Veroeros</a></li>\r\n");
      out.write("											</ul>\r\n");
      out.write("										</li>\r\n");
      out.write("										<li><a href=\"#\">Etiam Dolore</a></li>\r\n");
      out.write("										<li><a href=\"#\">Adipiscing</a></li>\r\n");
      out.write("										<li>\r\n");
      out.write("											<span class=\"opener\">Another Submenu</span>\r\n");
      out.write("											<ul>\r\n");
      out.write("												<li><a href=\"#\">Lorem Dolor</a></li>\r\n");
      out.write("												<li><a href=\"#\">Ipsum Adipiscing</a></li>\r\n");
      out.write("												<li><a href=\"#\">Tempus Magna</a></li>\r\n");
      out.write("												<li><a href=\"#\">Feugiat Veroeros</a></li>\r\n");
      out.write("											</ul>\r\n");
      out.write("										</li>\r\n");
      out.write("										<li><a href=\"#\">Maximus Erat</a></li>\r\n");
      out.write("										<li><a href=\"#\">Sapien Mauris</a></li>\r\n");
      out.write("										<li><a href=\"#\">Amet Lacinia</a></li>\r\n");
      out.write("									</ul>\r\n");
      out.write("								</nav>\r\n");
      out.write("\r\n");
      out.write("							<!-- Section -->\r\n");
      out.write("								<section>\r\n");
      out.write("									<header class=\"major\">\r\n");
      out.write("										<h2>Ante interdum</h2>\r\n");
      out.write("									</header>\r\n");
      out.write("									<div class=\"mini-posts\">\r\n");
      out.write("										<article>\r\n");
      out.write("											<a href=\"#\" class=\"image\"><img src=\"/tourapp/images/pic07.jpg\" alt=\"\" /></a>\r\n");
      out.write("											<p>Aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore aliquam.</p>\r\n");
      out.write("										</article>\r\n");
      out.write("										<article>\r\n");
      out.write("											<a href=\"#\" class=\"image\"><img src=\"/tourapp/images/pic08.jpg\" alt=\"\" /></a>\r\n");
      out.write("											<p>Aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore aliquam.</p>\r\n");
      out.write("										</article>\r\n");
      out.write("										<article>\r\n");
      out.write("											<a href=\"#\" class=\"image\"><img src=\"/tourapp/images/pic09.jpg\" alt=\"\" /></a>\r\n");
      out.write("											<p>Aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore aliquam.</p>\r\n");
      out.write("										</article>\r\n");
      out.write("									</div>\r\n");
      out.write("									<ul class=\"actions\">\r\n");
      out.write("										<li><a href=\"#\" class=\"button\">More</a></li>\r\n");
      out.write("									</ul>\r\n");
      out.write("								</section>\r\n");
      out.write("\r\n");
      out.write("							<!-- Section -->\r\n");
      out.write("								<section>\r\n");
      out.write("									<header class=\"major\">\r\n");
      out.write("										<h2>Get in touch</h2>\r\n");
      out.write("									</header>\r\n");
      out.write("									<p>Sed varius enim lorem ullamcorper dolore aliquam aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore. Proin sed aliquam facilisis ante interdum. Sed nulla amet lorem feugiat tempus aliquam.</p>\r\n");
      out.write("									<ul class=\"contact\">\r\n");
      out.write("										<li class=\"fa-envelope-o\"><a href=\"#\">information@untitled.tld</a></li>\r\n");
      out.write("										<li class=\"fa-phone\">(000) 000-0000</li>\r\n");
      out.write("										<li class=\"fa-home\">1234 Somewhere Road #8254<br />\r\n");
      out.write("										Nashville, TN 00000-0000</li>\r\n");
      out.write("									</ul>\r\n");
      out.write("								</section>\r\n");
      out.write("\r\n");
      out.write("							<!-- Footer -->\r\n");
      out.write("								<footer id=\"footer\">\r\n");
      out.write("									<p class=\"copyright\">&copy; Untitled. All rights reserved. Demo Images: <a href=\"https://unsplash.com\">Unsplash</a>. Design: <a href=\"https://html5up.net\">HTML5 UP</a>.</p>\r\n");
      out.write("								</footer>\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- Scripts -->\r\n");
      out.write("			<script src=\"/common/js/jquery.min.js\"></script>\r\n");
      out.write("			<script src=\"/common/js/skel.min.js\"></script>\r\n");
      out.write("			<script src=\"/common/js/util.js\"></script>\r\n");
      out.write("			<!--[if lte IE 8]><script src=\"/common/js/ie/respond.min.js\"></script><![endif]-->\r\n");
      out.write("			<script src=\"/common/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("	</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
